### ISSUE TITLE
how generate token with easy???

### ISSUE THREAD

**Issue by lordmen99** [Vidyo/helloworld-vidyo.io-android#1]
I Have try generate token, but its still confius. u have php generator for sample app

**Comment by pfuternik** [comment]
Hello,

We do not have a PHP generator but have Java, Python, JavaScript and C# (which is not yet on the site but I can provide to you if needed).

The token section of our documentation explains how to use and generate tokens:
https://developer.vidyo.io/documentation/4-1-6-2/getting-started#Tokens

Using the python script as an example, you would execute the following to generate a token:

python3 generateToken.py --key=ENTER_YOUR_KEY --appID=ENTER_YOUR_APP_ID --userName=user1 --expiresInSecs=10000

You can get your key and appID from the Dashboard page on vidyo.io :

https://developer.vidyo.io/dashboard

Let me know if that helps.

Thanks,
Phil

**Comment by jitendra1234567** [comment]
how i can get token in android studio without using command. I want to generate token inside app.

**Comment by jitendra1234567** [comment]
We can make http request which return token in json,string or xml formate.

https://vidyocreatetoken.appspot.com/on_get_token?developer_Key=bkhlkjh6&app_Id=kp09e.vidyo.io&expires_In_Secs=10000
This is not usefull.

**Comment by jitendra1234567** [comment]
Library  - generateToken.jar 

Library code-
              class GenerateToken 
               String payload = String.join(DELIM, PROVISION_TOKEN, jid, expires, vcard);

Android studio 3.0.1 is not able to Resolve  String.join()
how i can solve it.

**Comment by pfuternik** [comment]
Hi,

The token is supposed to be generated on the backend of your application. Your client android app should query your backend to get a token and then use the token to connect. Here are a few articles that may help, including a nice token generation video:

https://support.vidyo.io/hc/en-us/articles/115003127747-Generate-a-Token

https://support.vidyo.io/hc/en-us/articles/115004915647-Generate-Vidyo-io-Tokens

**Comment by mostafasaadamin** [comment]
How  i can create a token within android studio without using cmd i want to make every user enter my app will have his own Token without using cmd

**Comment by manojchahal** [comment]
hi can you share that how we can generated token inside the app's code in android

**Comment by pfuternik** [comment]
Hello, as previously mentioned the token should be generated on the backend and sent to your android client application. It compromises security by generating the token in the app itself. We have token generators available in various languages on our developer site.

**Comment by genarolaunchlabs** [comment]
Hello, any sample  code how to generate token from the  backend. I really stuck with generating token for a week now

**Comment by genarolaunchlabs** [comment]
generating a token in java is like this `java -jar generateToken.jar --key=3907f8fa000d4ae08e3a2a0507986d45 --appID=d85f88.vidyo.io --userName=user1 --expiresInSecs=10000` right. I could generate a token by running that on terminal and I'm able to do that. But how would I do that on the backend, any sample code would be much appreciated. Thanks

**Comment by pfuternik** [comment]
We do not have sample code, but I suggest you research how to setup your backend to handle a RESTful web service request. The request will tell your backend to generate a token and it will then send the token back to the client in a response message.

**Comment by genegershanok** [comment]
You can check out our Google App Engine sample that will generate a token based on your developer key: https://github.com/Vidyo/gae-simple-room

You can easily deploy it to the google cloud and host your application there.

**Comment by obperryo** [comment]
So I need this too. The issue is that I only need a working demo between a couple devices, and can kill/regen my key at any time. I don't have a backend resource to use at this time to get a token. Need a simpler temp solution to demo. Any ideas would be great!

**Comment by genegershanok** [comment]
If you control the endpoint, and for demo purposes only, you can generate a token with an appropriate expiration time and hardcore it into every endpoint you want to demo.

A generated token is akin to a temporary username/password combination. 

-gene

**Comment by jitendra1234567** [comment]
<?php
//echo "Token Generation Sample <br />";
        $DEV_KEY = "" ;            // Copy your dev key from vidyo.io dashboard
        $APP_ID = "" ;    // Copy your app Id from vidyo.io dashboard
        $username = "" ;          // Username, hard coded for debug purposes
        $expiresInSecs =10000;         // Generated token will expire after these many seconds

        // time() by default subtracts datetime(1970, 1, 1) from the datetime
        // on which we call it, therefore the number of seconds is smaller
        // by (pseudocode!) seconds("1970-01-01").
        // In Erlang, on the other hand, we get the actual number of seconds,
        // hence we adjust for this difference here.
        // IMPORTANT! A 64bit architecture is assumed! Otherwise, the timestamp
        // might be stored as a 32bit integer, therefore limiting the "capacity"
        // to 2038 (see https://en.wikipedia.org/wiki/Year_2038_problem).
        $EPOCH_SECONDS = 62167219200 ;
        $expires = $EPOCH_SECONDS + $expiresInSecs + time();

        //echo "<br />" ;
        //echo "Developer key" . "\t" ."\t" ."\t" . ":" . $DEV_KEY . "<br />" ;
        //echo "App ID          : " . $APP_ID . "<br />" ;
       // echo "Username        : " . $username . "<br />" ;
       // echo "Expires         : " . date("F j, Y, g:i a", $expiresInSecs + time()) . "<br />" ;

        $jid = $username . "@" . $APP_ID ;
        //echo "JID: " . $jid . "<br />" ;

        // Must place \0 within double quotes, not single quotes.
        $body = "provision" . "\0" . $jid . "\0" . $expires . "\0" . "" ;
        //echo "BODY: " . $body . "<br />" ;

        // Important to convert to UTF8. I found this is what made the difference.
        $utf8_body = utf8_encode( $body ) ;
       // echo "UTF8 BODY: " . $utf8_body . "<br />" ;

        // Ensure the SHA384 Algo is being used.
        $mac_hash = hash_hmac( "sha384", $utf8_body, $DEV_KEY ) ;
       // echo "HMAC (384): " . $mac_hash . "<br />" ;

        // Again, ensure \0 are encapsulated with double quotes. Single quotes does not append the null character to the string
        $serialized = $utf8_body . "\0" . $mac_hash ;
       // echo "SERIALIZED: " . $serialized . "<br />" ;

        // Base64 Encode the serialized string
        $b64_encoded = base64_encode( $serialized ) ;
       // echo "<br /> B64 ENCODED TOKEN :<br /><br />" . $b64_encoded . "<br />" ;

       echo $b64_encoded ;
    ?>

**Comment by obperryo** [comment]
What is this language... You stated earlier Android, this does not look
like java.  We are stuck on hmac shma384 encode.

**Comment by pfuternik** [comment]
This is Python but it doesn't matter. For your demo, you can take the approach that Gene suggested which is to hardcode the token into each endpoint.

**Comment by obperryo** [comment]
I can hard code a token and it works, but it will expire... I don't know
how long I could set a token for or if it will remain if I was to do
something like a year, so I was trying to just pull a token when I start
the app.

**Comment by pfuternik** [comment]
When you generate a token, you specify when it will expire.

**Comment by obperryo** [comment]
Oh, I see, I can just make a token good for 6 months and it will continue
to work until then if I hard code it. And if needed, I can go in the
account and expire early.

**Comment by pfuternik** [comment]
Its generally not a good idea to use the same token for such a long period of time, but yes, you technically can do that. However, there is no means to make the token expire. It just will no longer work if you don't have minutes remaining in your account.

**Comment by obperryo** [comment]
Will the token stop working if I delete the key used to make it from within
my video account? I was thinking it would.

**Comment by pfuternik** [comment]
Yes, that would do it.

**Comment by perk1990** [comment]
I Have try generate token, but its still confusing. Can any one tell how to generate token using php and how can i run python script in php to generate token. i am trying since last 1 week.

**Comment by alvarofpp** [comment]
Hello @perk1990. If you use Laravel, you can use this package that I developed: [`LaraStuffs/vidyo-token`](https://github.com/LaraStuffs/vidyo-token). If you don't use Laravel, but use PHP, you can use this class to generate the access token for Vidyo.io: [`VidyoToken.php`](https://github.com/LaraStuffs/vidyo-token/blob/master/src/VidyoToken.php), just change:
- `config('vidyo.default.username')` for your default username;
- `config('vidyo.default.seconds')` for the default seconds that you want;
- `config('vidyo.app_id')` for your application id;
- `config('vidyo.developer_key')` for your developer key.
