### ISSUE TITLE
is connectToRoomAsGuest available?

### ISSUE THREAD

**Issue by JVHE** [Vidyo/helloworld-vidyo.io-android#11]
Hi. I was found these functions in Connect class.
connectToRoomAsGuest(...)
connectToRoomWithKey(...)
connectToRoomWithTokenAndKey(...)
connectToRoomWithId(...)
connectToRoomWithTokenAndId(...)
connectToRoomAsGuest(...)
I'm trying to implement live video streaming app using this library. But I cannot found any usages and guides of these functions. Is it available?

**Comment by pfuternik** [comment]
Hello, you can ignore these functions, as they are used to connect to a legacy system, not Vidyo.io. To connect to Vidyo.io, simply use the connect(...) API.
