### ISSUE TITLE
App is restarting randomly.

### ISSUE THREAD

**Issue by yadavshivam3000** [Vidyo/helloworld-vidyo.io-android#13]
I am facing a issue whenever I finished calling then app crashed and new process starts randomly.

**Comment by pfuternik** [comment]
Hello, are you running this project exactly as is or are there any modifications? Can you insert a breakpoint and determine where the crash is occurring?

**Comment by yadavshivam3000** [comment]
Hi,
I solved the issue. Issue was generating calling of disable method without calling disconnect method of connector.

But the documentation didn't say it . Never I get any logs in logcat for the crash so it was hard to find the issue.
Anyways thanks for your support.

**Comment by pfuternik** [comment]
Glad you found the root cause. I will then close this issue.
