### ISSUE TITLE
This Example "helloworld-vidyo.io-android" crashes on deployment to Android Device

### ISSUE THREAD

**Issue by QuantamKawts** [Vidyo/helloworld-vidyo.io-android#4]
OS : Ubuntu 16
    IDE : Android Studio 3.0

Target Devices:
   Emulator : API 27 NEXUS
   Device : Samsung Galaxy S8

**Steps Taken:**

1. Downloaded  "**helloworld-vidyo.io-android**" Project from:
 https://github.com/Vidyo/helloworld-vidyo.io-android
2. Import VidyoIODemo project In Android Studio
3. Create directory in VidyoIODemo/app/ named "libs"
4. Install the VidyoClient-AndroidSDK contents into the "libs" folder
5. Generated String token using the generate.py file
6. Entered the generated String token on the MainActivity.java file line 32
7. Built and Run the project. Targeted the apk to install on the Emulator and physical phone
8. Right on load, the app VidyoIODemo crashes instantly. Loop crashes when restarting the app on device
9. Ran the app again with debugger and found fatal error : 
 **`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.pfuternik.vidyoiodemo-6P_jGXzsGvC5MVkQo5veOQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.pfuternik.vidyoiodemo-6P_jGXzsGvC5MVkQo5veOQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libVidyoClient.so"`**
          
Attachments are included in this issue
[errorVidyio.txt](https://github.com/Vidyo/helloworld-vidyo.io-android/files/1456338/errorVidyio.txt)
![screenshot_2017-11-08_23-38-47](https://user-images.githubusercontent.com/31378485/32589102-9ac08946-c4e0-11e7-82a6-6f77f8253994.png)

If possible, please either troubleshoot this issue or redesign/update this project so it can be implemented and demonstrated properly

Thank you

**Comment by pfuternik** [comment]
Hi, 

It appears that you copied the files from the VidyoClient-AndroidSDK to the wrong location. The instructions note:

"Copy all files located at VidyoClient-AndroidSDK/lib/android to the VidyoIODemo/app/libs directory."

See attached screenshot for the expected directory structure. I have verified that this app still works as expected.

Let me know if you get it to work!

Thanks,
Philip

<img width="961" alt="androiddirstructure" src="https://user-images.githubusercontent.com/24925258/32971845-2ee8dc4e-cbbd-11e7-8d2d-234a8def52e9.png">
