### ISSUE TITLE
creating token

### ISSUE THREAD

**Issue by mostafasaadamin** [Vidyo/helloworld-vidyo.io-android#5]
How I can create Token inside my android studio i want user enter his username then the Token created for him How i can do that  with out using CMD Please help

**Comment by pfuternik** [comment]
The token is supposed to be generated on the backend of your application. Your client android app should query your backend to get a token and then use the token to connect. Here are a few articles that may help, including a nice token generation video:

https://support.vidyo.io/hc/en-us/articles/115003127747-Generate-a-Token

https://support.vidyo.io/hc/en-us/articles/115004915647-Generate-Vidyo-io-Tokens

Its not secure to create it inside the app, but if you must then you can use the Java generator here: https://static.vidyo.io/4.1.20.3/utils/generateToken.jar

**Comment by NakWarsii** [comment]
what exactly the work of token ?
why we need this ?

**Comment by tmelko-vidyo** [comment]
A token is a short-lived authentication credential that grants access to the Vidyo.io service on behalf of the developer to a specific user. In general, it's a holder of your application credentials, access expiration, endpoint for subscription charging etc.
